[[main]]
none = "none"

#[[main]]
#name = "Interests"
#pageRef = "interests"
#weight = 1

[[main]]
name = "Projects"
pageRef = "personal-projects"
weight = 2

#[[main]]
#name = "Professional Projects"
#parent = "Projects"
#pageRef = "professional-projects"
#weight = 2

#[[main]]
#name = "Personal Projects"
#parent = "Projects"
#pageRef = "personal-projects"
#weight = 3

[[footer]]
none = "none"
